rsvg-convert -f pdf -o pdf/day-0-layout.pdf         svg/day-0-layout.svg
rsvg-convert -f pdf -o pdf/day-1-layout.pdf         svg/day-1-layout.svg
rsvg-convert -f pdf -o pdf/day-2-layout.pdf         svg/day-2-layout.svg
rsvg-convert -f pdf -o pdf/day-3-layout.pdf         svg/day-3-layout.svg
rsvg-convert -f pdf -o pdf/day-4-layout.pdf         svg/day-4-layout.svg
rsvg-convert -f pdf -o pdf/day-5-layout.pdf         svg/day-5-layout.svg
rsvg-convert -f pdf -o pdf/day-6-layout.pdf         svg/day-6-layout.svg
rsvg-convert -f pdf -o pdf/week-layout.pdf          svg/week-layout.svg
rsvg-convert -f pdf -o pdf/future-5yr-layout.pdf    svg/future-5yr-layout.svg
rsvg-convert -f pdf -o pdf/future-1yr-layout.pdf    svg/future-1yr-layout.svg
rsvg-convert -f pdf -o pdf/future-12w-layout.pdf    svg/future-12w-layout.svg
rsvg-convert -f pdf -o pdf/goal-layout.pdf          svg/goal-layout.svg
rsvg-convert -f pdf -o pdf/habit-layout.pdf         svg/habit-layout.svg
rsvg-convert -f pdf -o pdf/divider-calendar.pdf     svg/divider-calendar.svg
rsvg-convert -f pdf -o pdf/divider-goals.pdf        svg/divider-goals.svg
rsvg-convert -f pdf -o pdf/divider-vision.pdf       svg/divider-vision.svg
rsvg-convert -f pdf -o pdf/divider-week-1.pdf       svg/divider-week-1.svg
rsvg-convert -f pdf -o pdf/divider-week-2.pdf       svg/divider-week-2.svg
rsvg-convert -f pdf -o pdf/divider-week-3.pdf       svg/divider-week-3.svg
rsvg-convert -f pdf -o pdf/divider-week-4.pdf       svg/divider-week-4.svg
rsvg-convert -f pdf -o pdf/divider-week-5.pdf       svg/divider-week-5.svg
rsvg-convert -f pdf -o pdf/divider-week-6.pdf       svg/divider-week-6.svg
rsvg-convert -f pdf -o pdf/divider-week-7.pdf       svg/divider-week-7.svg
rsvg-convert -f pdf -o pdf/divider-week-8.pdf       svg/divider-week-8.svg
rsvg-convert -f pdf -o pdf/divider-week-9.pdf       svg/divider-week-9.svg
rsvg-convert -f pdf -o pdf/divider-week-10.pdf      svg/divider-week-10.svg
rsvg-convert -f pdf -o pdf/divider-week-11.pdf      svg/divider-week-11.svg
rsvg-convert -f pdf -o pdf/divider-week-12.pdf      svg/divider-week-12.svg
