rsvg-convert -f pdf -o pdf/divider-calendar.pdf  svg/divider-calendar.svg
rsvg-convert -f pdf -o pdf/divider-goals.pdf     svg/divider-goals.svg
rsvg-convert -f pdf -o pdf/divider-month-1.pdf   svg/divider-month-1.svg
rsvg-convert -f pdf -o pdf/divider-month-2.pdf   svg/divider-month-2.svg
rsvg-convert -f pdf -o pdf/divider-month-3.pdf   svg/divider-month-3.svg
rsvg-convert -f pdf -o pdf/divider-vision.pdf    svg/divider-vision.svg
rsvg-convert -f pdf -o pdf/goal-layout.pdf       svg/goal-layout.svg
rsvg-convert -f pdf -o pdf/month-0.pdf           svg/month-0.svg
rsvg-convert -f pdf -o pdf/month-1.pdf           svg/month-1.svg
rsvg-convert -f pdf -o pdf/page-00.pdf           svg/page-00.svg
rsvg-convert -f pdf -o pdf/page-01.pdf           svg/page-01.svg
rsvg-convert -f pdf -o pdf/page-02.pdf           svg/page-02.svg
rsvg-convert -f pdf -o pdf/page-03.pdf           svg/page-03.svg
rsvg-convert -f pdf -o pdf/page-04.pdf           svg/page-04.svg
rsvg-convert -f pdf -o pdf/page-05.pdf           svg/page-05.svg
rsvg-convert -f pdf -o pdf/page-06.pdf           svg/page-06.svg
rsvg-convert -f pdf -o pdf/page-07.pdf           svg/page-07.svg
rsvg-convert -f pdf -o pdf/page-08.pdf           svg/page-08.svg
rsvg-convert -f pdf -o pdf/page-09.pdf           svg/page-09.svg
rsvg-convert -f pdf -o pdf/page-10.pdf           svg/page-10.svg
rsvg-convert -f pdf -o pdf/page-11.pdf           svg/page-11.svg
rsvg-convert -f pdf -o pdf/test.pdf              svg/test.svg
rsvg-convert -f pdf -o pdf/week-chcklst-back.pdf svg/week-chcklst-back.svg
rsvg-convert -f pdf -o pdf/week-chcklst-frnt.pdf svg/week-chcklst-frnt.svg
