rsvg-convert -f pdf -o pdf/divider-calendar.pdf  svg/divider-calendar.svg
rsvg-convert -f pdf -o pdf/divider-goals.pdf     svg/divider-goals.svg
rsvg-convert -f pdf -o pdf/divider-month-1.pdf   svg/divider-month-1.svg
rsvg-convert -f pdf -o pdf/divider-month-2.pdf   svg/divider-month-2.svg
rsvg-convert -f pdf -o pdf/divider-month-3.pdf   svg/divider-month-3.svg
rsvg-convert -f pdf -o pdf/divider-vision.pdf    svg/divider-vision.svg
rsvg-convert -f pdf -o pdf/0__title-page.pdf     svg/0__title-page.svg
rsvg-convert -f pdf -o pdf/1__vision-0.pdf       svg/1__vision-0.svg
rsvg-convert -f pdf -o pdf/1__vision-1.pdf       svg/1__vision-1.svg
rsvg-convert -f pdf -o pdf/1__vision-2.pdf       svg/1__vision-2.svg
rsvg-convert -f pdf -o pdf/1__vision-3.pdf       svg/1__vision-3.svg
rsvg-convert -f pdf -o pdf/3__month-0.pdf        svg/3__month-0.svg
rsvg-convert -f pdf -o pdf/3__month-1.pdf        svg/3__month-1.svg
rsvg-convert -f pdf -o pdf/4__week-0.pdf         svg/4__week-0.svg
rsvg-convert -f pdf -o pdf/4__week-1.pdf         svg/4__week-1.svg
rsvg-convert -f pdf -o pdf/4__week-2.pdf         svg/4__week-2.svg
rsvg-convert -f pdf -o pdf/4__week-3.pdf         svg/4__week-3.svg
rsvg-convert -f pdf -o pdf/4__week-4.pdf         svg/4__week-4.svg
rsvg-convert -f pdf -o pdf/4__week-5.pdf         svg/4__week-5.svg
rsvg-convert -f pdf -o pdf/4__week-6.pdf         svg/4__week-6.svg
rsvg-convert -f pdf -o pdf/4__week-7.pdf         svg/4__week-7.svg
rsvg-convert -f pdf -o pdf/2__goal-layout-0.pdf  svg/goal-layout.svg
rsvg-convert -f pdf -o pdf/2__goal-layout-1.pdf  svg/goal-layout.svg
rsvg-convert -f pdf -o pdf/week-chcklst-back.pdf svg/week-chcklst-back.svg
rsvg-convert -f pdf -o pdf/week-chcklst-frnt.pdf svg/week-chcklst-frnt.svg
